version: '2'
services:
  devpi:
    build: .
    image: swind/devpi
    ports:
     - "3142:3142"
     - "3141:3141"
    volumes:
     - ./devpi:/root/devpi
    environment:
     - DEVPI_SERVERDIR=/root/devpi
     - DEVPI_PASSWORD=12345
     - DEVPI_MIRROR_CACHE_EXPIRY=86400
